#!/usr/bin/env python3
# this_file: scripts/generate_corpus_index.py
"""Render a human-readable corpus index (file -> features exercised).

Reads the same corpus that ``generate_coverage_report.py`` measures and writes
a Jekyll page at ``docs/corpus-index.md`` with one row per fixture: its license
bucket, whether it is variable, and the structural features it exercises
(glyphs, axes, kerning, anchors, hints, components, masks, images). CI keeps
this page current with ``--check``.

Usage:
    python scripts/generate_corpus_index.py            # rewrite the page
    python scripts/generate_corpus_index.py --check     # exit 1 if stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

import generate_coverage_report as coverage  # noqa: E402

OUTPUT = ROOT / "docs" / "corpus-index.md"

# Human column label -> counts key in the coverage report.
FEATURE_COLUMNS = [
    ("Glyphs", "glyph_containers"),
    ("Axes", "axis_markers"),
    ("Kerning", "kerning_markers"),
    ("Anchors", "anchor_markers"),
    ("Hints", "hint_markers"),
    ("Components", "component_markers"),
    ("Masks", "mask_markers"),
    ("Images", "image_markers"),
]

FRONT_MATTER = """---
title: Corpus index
layout: default
nav_order: 4
---

<!-- Generated by scripts/generate_corpus_index.py. Do not edit by hand. -->

# Corpus index

Every fixture in the corpus, with the structural features it exercises. Counts
are structural markers found in the VFJ JSON, not glyph-perfect tallies — they
show at a glance which files are worth reaching for when you need a font with,
say, kerning or multiple axes.
"""


def render(report: dict) -> str:
    """Return the full Markdown page for the given coverage report."""

    header = "| File | License | Variable | " + " | ".join(name for name, _ in FEATURE_COLUMNS) + " |"
    divider = "|" + "---|" * (3 + len(FEATURE_COLUMNS))
    lines = [
        FRONT_MATTER,
        f"Total fixtures: **{report['total_files']}** "
        f"({report['variable_files']} variable, {report['static_files']} static).",
        "",
        header,
        divider,
    ]
    for entry in report["files"]:
        counts = entry["counts"]
        cells = [f"`{entry['path']}`", entry["license_bucket"], "yes" if entry["is_variable"] else "no"]
        cells.extend(str(counts[key]) for _, key in FEATURE_COLUMNS)
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify the page is current without rewriting it")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Regenerate or verify the corpus index page."""

    args = parse_args(argv)
    report = coverage.build_report(coverage.CORPUS)
    expected = render(report)

    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print("docs/corpus-index.md is out of date; run scripts/generate_corpus_index.py", file=sys.stderr)
            return 1
        print("docs/corpus-index.md is up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
